### ISSUE TITLE
Issue with next 14.3.0-canary.54

### ISSUE THREAD

**Issue by FairyPenguin** [devjiwonchoi/remote-mdx#10] opened 2024-05-10 19:20 UTC
Hi @devjiwonchoi, Hope you are doing well.

I want to thank you for this package.

The package broke once i updated to the latest beta of nextjs 14.3.0-canary.54

i get this error 
```

Warning: Only plain objects can be passed to Client Components from Server Components. Classes or other objects with methods are not supported.
  <article className=... children={{$$typeof: ..., type: ..., key: Null, ref: ..., props: ..., _owner: ..., _store: ...}}>
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ⨯ Error: Functions are not valid as a child of Client Components. This may happen if you return MDXContent instead of <MDXContent /> from render. Or maybe you meant to call this function rather than return it.
  {$$typeof: ..., type: function MDXContent, key: ..., ref: ..., props: ..., _owner: ..., _store: ...}
                        ^^^^^^^^^^^^^^^^^^^
    at stringify (<anonymous>)
digest: "1723576498"

```
I;m using the compileMDX function 

`import { compileMDX } from 'remote-mdx/rsc'`

for now i rolled-back to the previous beta version and everything seems to be working fine

**Comment by devjiwonchoi** [comment] 2024-05-11 13:25
@FairyPenguin Hi, I'd love to solve your issue, can you provide a minimum reproduction so I can fix it ASAP for you?
I'm also using `next@canary` but am not observing the issue ATM.

**Comment by FairyPenguin** [comment] 2024-05-11 19:32
> @FairyPenguin Hi, I'd love to solve your issue, can you provide a minimum reproduction so I can fix it ASAP for you? I'm also using `next@canary` but am not observing the issue ATM.

Thanks,I sent you an invite to the repo because it's private 
![image](https://github.com/devjiwonchoi/remote-mdx/assets/37639473/f1c8091d-8673-4304-8fa6-7cb88b0105e1)

**Comment by devjiwonchoi** [comment] 2024-05-11 20:19
@FairyPenguin hi, please try the latest `remote-mdx@0.0.8`, seem to work fine!

**Comment by FairyPenguin** [comment] 2024-05-11 23:15
> @FairyPenguin hi, please try the latest `remote-mdx@0.0.8`, seem to work fine!

Thanks worked like a charm, Appreciate your help and support 💙

Whenever you have time of-course, i need to understand something about this package it's having 3 main functions right? compileMDX, serialize and MDXRemote

I don't understand the difference between them until now,I'm only using the compileMDX and it's working do I need the other 2 functions and what they are for I don't know 🤦‍♂️

**Comment by FairyPenguin** [comment] 2024-05-11 23:18
Another thing I noticed there is a small mistake in the docs 

- import { serialize } from 'next-mdx-remote/serialize'
+ import { serialize } from 'remote-mdx/serialize'

- import { MDXRemote } from 'next-mdx-remote'
+ import { MDXRemote } from 'remote-mdx'

- import { MDXRemote } from 'next-mdx-remote/rsc'
+ import { MDXRemote } from 'remote-mdx/rsc'

here there is a duplication for the `MDXRemote` the third one should be `compileMDX` 

if you need me to do it as a pull-request just tell me.

**Comment by devjiwonchoi** [comment] 2024-05-12 03:13
@FairyPenguin Hi, this package is currently a fork of `next-mdx-remote`, behaves the same as it is.

`MDXRemote` is a React Component that renders from a given MDX string, whereas `compileMDX` **parses** a given "possible MDX string" into two outputs: [`frontmatter`](https://jekyllrb.com/docs/front-matter/) and `content`.


I'd recommend you to take a look at [here](https://github.com/hashicorp/next-mdx-remote?tab=readme-ov-file#react-server-components-rsc--nextjs-app-directory-support), since it describes well on your doubts. Feel free to ask more if that's not enough, I'd be happy to answer.

**Comment by devjiwonchoi** [comment] 2024-05-12 03:17
> here there is a duplication for the MDXRemote the third one should be compileMDX

Furthermore there's two MDXRemote on the example is because the `MDXRemote` differs between `remote-mdx` and `remote-mdx/rsc`, do you think we should add `compileMDX` as well for explaining it's a drop-in replacement?

**Comment by devjiwonchoi** [comment] 2024-05-12 04:52
Closing this as resolved!

**Closed as completed by devjiwonchoi** 2024-05-12 04:52 UTC

**Comment by FairyPenguin** [comment] 2024-05-14 08:10
> > here there is a duplication for the MDXRemote the third one should be compileMDX
> 
> Furthermore there's two MDXRemote on the example is because the `MDXRemote` differs between `remote-mdx` and `remote-mdx/rsc`, do you think we should add `compileMDX` as well for explaining it's a drop-in replacement?

Yeah it will be better to add compileMDX

**Comment by devjiwonchoi** [comment] 2024-05-14 08:12
@FairyPenguin Feel free to send a PR! Thanks 😄
